<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--
    Cabinet Row Macro

    Creates a row of cabinets (left or right) with proper positioning.
    Each cabinet contains box placement frames for runtime box spawning.
  -->

  <xacro:macro name="cabinet_row" params="side parent_link config">

    <!-- Get row configuration -->
    <xacro:property name="row_config" value="${config['cabinet_rows'][side]}"/>
    <xacro:property name="row_offset" value="${row_config['offset']}"/>
    <xacro:property name="cabinets" value="${row_config['cabinets']}"/>

    <!-- Simplified side naming: side_l or side_r -->
    <xacro:property name="side_abbrev" value="${'l' if side == 'left' else 'r'}"/>

    <!-- Row base link -->
    <link name="side_${side_abbrev}"/>

    <!-- Fixed joint to parent -->
    <joint name="side_${side_abbrev}_to_base" type="fixed">
      <parent link="${parent_link}"/>
      <child link="side_${side_abbrev}"/>
      <origin xyz="${row_offset['x']} ${row_offset['y']} ${row_offset['z']}" rpy="0 0 0"/>
    </joint>

    <!-- Include cabinet macro -->
    <xacro:include filename="$(find manipulator_description)/urdf/cabinet.urdf.xacro"/>

    <!-- Generate cabinets -->
    <!-- Cabinet dimensions -->
    <xacro:property name="cab_width" value="${config['cabinet_dimensions']['exterior']['x']}"/>
    <xacro:property name="num_cabinets" value="${len(cabinets)}"/>

    <!-- Explicit cabinet generation (xacro doesn't support dynamic iteration) -->
    <!-- Cabinet 1 -->
    <xacro:if value="${num_cabinets &gt;= 1}">
      <xacro:property name="cab1_size" value="${cabinets[0]['size']}"/>
      <xacro:property name="cab1_x" value="${0.0 if side == 'left' else 1 * cab_width}"/>
      <xacro:cabinet
        side="${side}"
        cabinet_num="1"
        size_name="${cab1_size}"
        parent_link="side_${side_abbrev}"
        position_x="${cab1_x}"
        position_y="0.0"
        position_z="0.0"
        rotation_z="${0.0 if side == 'left' else 3.14159}"
        config="${config}"/>
    </xacro:if>

    <!-- Cabinet 2 -->
    <xacro:if value="${num_cabinets &gt;= 2}">
      <xacro:property name="cab2_size" value="${cabinets[1]['size']}"/>
      <xacro:property name="cab2_x" value="${1 * cab_width if side == 'left' else 2 * cab_width}"/>
      <xacro:cabinet
        side="${side}"
        cabinet_num="2"
        size_name="${cab2_size}"
        parent_link="side_${side_abbrev}"
        position_x="${cab2_x}"
        position_y="0.0"
        position_z="0.0"
        rotation_z="${0.0 if side == 'left' else 3.14159}"
        config="${config}"/>
    </xacro:if>

    <!-- Cabinet 3 -->
    <xacro:if value="${num_cabinets &gt;= 3}">
      <xacro:property name="cab3_size" value="${cabinets[2]['size']}"/>
      <xacro:property name="cab3_x" value="${2 * cab_width if side == 'left' else 3 * cab_width}"/>
      <xacro:cabinet
        side="${side}"
        cabinet_num="3"
        size_name="${cab3_size}"
        parent_link="side_${side_abbrev}"
        position_x="${cab3_x}"
        position_y="0.0"
        position_z="0.0"
        rotation_z="${0.0 if side == 'left' else 3.14159}"
        config="${config}"/>
    </xacro:if>

    <!-- Cabinet 4 -->
    <xacro:if value="${num_cabinets &gt;= 4}">
      <xacro:property name="cab4_size" value="${cabinets[3]['size']}"/>
      <xacro:property name="cab4_x" value="${3 * cab_width if side == 'left' else 4 * cab_width}"/>
      <xacro:cabinet
        side="${side}"
        cabinet_num="4"
        size_name="${cab4_size}"
        parent_link="side_${side_abbrev}"
        position_x="${cab4_x}"
        position_y="0.0"
        position_z="0.0"
        rotation_z="${0.0 if side == 'left' else 3.14159}"
        config="${config}"/>
    </xacro:if>

    <!-- Add more cabinet slots if needed (5, 6, 7, 8...) -->
    <!-- Each follows the same pattern with incremented numbers -->

  </xacro:macro>

</robot>
